site_name: EasyStock
nav:
    - Início: index.md
    - Documentação:
        - 'Visão geral do produto': 'visao-geral-produto.md'
        - 'Visão geral do projeto': 'visao-geral-projeto.md'
        - 'Processo de desenvolvimento de software': 'processo-de-desenvolvimento-de-software.md'
        - 'Lições aprendidas': 'licoes-aprendidas.md'
    - Backlog:
        - 'Definições': 'dod-dor.md'
        - 'Requisitos': 'requisitosF-NF.md'
        - 'Critérios de Aceitação': 'criterios.md'
        - 'MVP': 'mvp1-mvp2.md'
    - Arquitetura: 'arquitetura.md'     
    - Entregas:
        - 'Unidade 1': 'unidade1.md'
        
theme: 
    name: material
    palette:
    - scheme: slate
      primary: cyan
    
  